language: node_js
node_js:
  - "iojs"
  - "8"
before_script:
  - yarn install --frozen-lockfile
notifications:
  email:
    recipients:
      - herezk@gmail.com
    on_success: change
    on_failure: always
